[postgres]
host = "mamdb.cet.uct.ac.za"
port = 5432
dbname = "mam107h"
user = "jjaftha"
password = "numeracy"

[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "b7f4e8c1a2d34e5f9c6b7a8d9e0f1c2b"

[auth.google]
client_id = "90590965070-o3ibthgb9gcvr1ti1h0co17tp76qc8o4.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url="https://accounts.google.com/.well-known/openid-configuration"

